### ISSUE TITLE
Limitation 

### ISSUE THREAD

**Issue by AmanBhatnagar12** [AliceOSClassic/AliceCalc#2]
In Next release v0.12 pre Alpha
Please include the feature 
#1 . Ability to add numbers as per user preference 
#2 . Automatically Displaying Enter the 1/2/3rd number 
or Adding Multiple numbers in One line and just by Symbol performing and displaying the result .
This would be great , 
All the Best 👍
😊

**Comment by AmanBhatnagar12** [comment]
Hi

**Comment by AliceOSClassic** [comment]
> In Next release v0.12 pre Alpha Please include the feature #1 . Ability to add numbers as per user preference #2 . Automatically Displaying Enter the 1/2/3rd number or Adding Multiple numbers in One line and just by Symbol performing and displaying the result . This would be great , All the Best 👍 😊
